apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: jtamayo89/mpago_data:0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
          name: flaskappbport
---
kind: Service
apiVersion: v1
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  ports:
  - name: flask-app
    port: 5000
    nodePort : 31783 
  #type: LoadBalancer
  type: NodePort
  selector:
    app: flask-app